#!/usr/bin/env python3
"""
toon_to_csv.py — Convert a TOON tabular block back to a CSV file.

Reads from stdin or --input file. Writes to --output file or stdout.
Only handles the tabular array format generated by csv_to_toon.py:
  key[N]{field1,field2,...}:
    val1,val2,...

Usage:
  echo "<toon>" | python scripts/toon_to_csv.py --output result.csv
  python scripts/toon_to_csv.py --input response.toon --output result.csv
  python scripts/toon_to_csv.py --input response.toon  # prints CSV to stdout

# Run: python scripts/toon_to_csv.py --input sample.toon --output out.csv
"""
from __future__ import annotations

import argparse
import csv
import re
import sys
from typing import Sequence


_HEADER_RE = re.compile(
    r"^\s*\S+\[(\d+)(?:\\t|\|)?\]\{([^}]*)\}\s*:\s*$"
)

_ESCAPE_MAP = {"\\\\": "\\", '\\"': '"', "\\n": "\n", "\\r": "\r", "\\t": "\t"}


def _unescape(s: str) -> str:
    """Decode TOON escape sequences inside a quoted string."""
    result = []
    i = 0
    while i < len(s):
        if s[i] == "\\" and i + 1 < len(s):
            two = s[i : i + 2]
            if two in _ESCAPE_MAP:
                result.append(_ESCAPE_MAP[two])
                i += 2
                continue
        result.append(s[i])
        i += 1
    return "".join(result)


def _split_row(line: str, delimiter: str) -> list[str]:
    """Split a TOON data row respecting double-quoted fields."""
    values: list[str] = []
    current: list[str] = []
    in_quote = False
    i = 0

    while i < len(line):
        ch = line[i]
        if ch == '"' and not in_quote:
            in_quote = True
            i += 1
            continue
        if ch == '"' and in_quote:
            if i + 1 < len(line) and line[i + 1] == '"':
                current.append('"')
                i += 2
                continue
            in_quote = False
            i += 1
            continue
        if ch == "\\" and in_quote and i + 1 < len(line):
            two = line[i : i + 2]
            if two in _ESCAPE_MAP:
                current.append(_ESCAPE_MAP[two])
                i += 2
                continue
        if ch == delimiter and not in_quote:
            values.append("".join(current))
            current = []
            i += 1
            continue
        current.append(ch)
        i += 1

    values.append("".join(current))
    return values


def _detect_delimiter(header_line: str) -> str:
    """Detect the TOON array delimiter from the header."""
    bracket_content = re.search(r"\[(\d+)([^]]*)\]", header_line)
    if bracket_content:
        suffix = bracket_content.group(2)
        if "\\t" in suffix:
            return "\t"
        if "|" in suffix:
            return "|"
    return ","


def _parse_toon(text: str) -> list[dict[str, str]]:
    """Parse a TOON tabular block and return a list of row dicts."""
    lines = text.splitlines()

    header_line: str | None = None
    header_line_idx = -1
    for i, line in enumerate(lines):
        if _HEADER_RE.match(line):
            header_line = line.strip()
            header_line_idx = i
            break

    if header_line is None:
        print(
            "Error: no TOON tabular header found.\n"
            "Expected format: key[N]{field1,field2,...}:",
            file=sys.stderr,
        )
        sys.exit(1)

    m = _HEADER_RE.match(header_line)
    assert m is not None
    declared_count = int(m.group(1))
    field_str = m.group(2)

    delimiter = _detect_delimiter(header_line)
    fields = [f.strip() for f in field_str.split(delimiter if delimiter != "," else ",")]

    data_lines = [
        line[2:] if line.startswith("  ") else line.lstrip()
        for line in lines[header_line_idx + 1 :]
        if line.strip()
    ]

    if len(data_lines) != declared_count:
        print(
            f"Warning: declared count [{declared_count}] does not match "
            f"actual row count {len(data_lines)}. "
            "LLM output may have been truncated.",
            file=sys.stderr,
        )

    rows: list[dict[str, str]] = []
    for line in data_lines:
        values = _split_row(line, delimiter)
        if len(values) != len(fields):
            print(
                f"Warning: row has {len(values)} values, expected {len(fields)}. "
                f"Row: {line!r}",
                file=sys.stderr,
            )
            while len(values) < len(fields):
                values.append("")
            values = values[: len(fields)]
        rows.append(dict(zip(fields, values)))

    return rows


def _write_csv(rows: list[dict[str, str]], output_path: str | None) -> None:
    if not rows:
        if output_path:
            open(output_path, "w").close()
        return

    fields = list(rows[0].keys())

    if output_path:
        with open(output_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fields)
            writer.writeheader()
            writer.writerows(rows)
    else:
        writer = csv.DictWriter(sys.stdout, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def _parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert a TOON tabular block to CSV."
    )
    parser.add_argument(
        "--input", "-i", default=None,
        help="Path to TOON input file (default: stdin)"
    )
    parser.add_argument(
        "--output", "-o", default=None,
        help="Path to output CSV file (default: stdout)"
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> None:
    args = _parse_args(argv)

    if args.input:
        try:
            with open(args.input, encoding="utf-8") as f:
                toon_text = f.read()
        except FileNotFoundError:
            print(f"Error: file not found: {args.input}", file=sys.stderr)
            sys.exit(1)
    else:
        toon_text = sys.stdin.read()

    rows = _parse_toon(toon_text)
    _write_csv(rows, args.output)

    if args.output:
        print(f"OK: wrote {len(rows)} rows to {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
